language: php
php:
  - 5.5
  - 5.4
  - 5.3
before_install:
  - cd ./soen390
install:
  - composer install --dev
script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -c phpunit.xml --coverage-text --debug
after_script:
  - php ./vendor/bin/coveralls -v
